# backend/nixpacks.toml

# We are overriding the 'setup' phase to provide a correct list of system packages.
[phases.setup]
pkgs = ["pkgs.python311", "pkgs.gcc", "pkgs.pipenv"]

# We can also explicitly define the start command here.
# This is often clearer than a Procfile and takes precedence.
[start]
cmd = "pipenv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"